### ISSUE TITLE
Focusable Item demo broken

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-item#14]
The Valo theme sets outline to [none](https://github.com/vaadin/vaadin-item/blob/master/theme/valo/vaadin-item.html#L21) so the demo needs to restore it [here](https://github.com/vaadin/vaadin-item/blob/master/demo/item-basic-demos.html#L21): instead of just setting the `outline-color` we need to also set the style and width (probably initial values for those).

**Comment by jouni** [comment]
Oh, I never realized there was a demo for a plain focusable item. My bad.

**Comment by jouni** [comment]
I think the `outline: none;` definition could be moved to list-box styles instead.

**Comment by web-padawan** [comment]
Fixed in 7b32eda and vaadin/vaadin-list-box@1e30f05
