### ISSUE TITLE
Introduce a block container for the slotted content

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-item#17]
Currently, Lumo specifies the host as a flex container. This might come as a surprise to developers when elements are not wrapped normally but placed on the same line horizontally.

We should consider adding a `<div>` wrapper for the slotted content.

At the same time, we should consider if we would like to do the same for `vaadin-combo-box-item` (maybe actually extend `vaadin-item`). It currently has a [wrapper for the `label` property](https://github.com/vaadin/vaadin-combo-box/blob/master/src/vaadin-combo-box-item.html#L20), and we could just introduce a `<slot>` inside that (and change it span -> div).

**Comment by jouni** [comment]
@platosha, @web-padawan: should we still try to push this change forward? Seems like it’s now or never (or until the next major version) 😃

**Comment by jouni** [comment]
Though, as discussed in https://github.com/vaadin/vaadin-notification/issues/52, we plan to introduce a flex container for the notification content container.

It’s a little different there, though, as changing it back to a block container with a theme doesn’t break the theme otherwise, it only affects the elements provided by the developer.

Whereas in the item, the selection checkmark expects the host to be a flex container. But, on the other hand, the checkmark could be absolutely positioned, avoiding the need for a flex container in the first place.

I know, it’s complicated 😄

**Comment by web-padawan** [comment]
Since the `vaadin-item` is intended to be used mainly for single-line content, I'm ok with the flex container.

At the same time, I would expect the checkmark to use absolute positioning, in order not to affect content placed into the item, in case if the user sets `justify-content: space-between`. Right now, if you open the latest demo with "Custom Content" and set this property, the content gets aligned in an unexpected way because of the checkmark.

**Comment by jouni** [comment]
> Since the vaadin-item is intended to be used mainly for single-line content, I'm ok with the flex container.

Not really. A common use case is to have a main text an a subtext (e.g. Name and email underneath).

> I would expect the checkmark to use absolute positioning

The original reason for using flex was that it was easy to omit the space reserved for the checkmark when using vaadin-list-box inside a vaadin-context-menu, by setting `display: none` for the checkmark. But I suppose overriding the host padding will be as simple.

**Comment by web-padawan** [comment]
So this is what I mean when talking about the checkmark and user content:

### Current

![screen shot 2018-02-22 at 11 12 23](https://user-images.githubusercontent.com/10589913/36529625-8c186560-17c1-11e8-9de3-5e5233bf9408.png)

### Expected

![screen shot 2018-02-22 at 11 14 05](https://user-images.githubusercontent.com/10589913/36529639-918ff68e-17c1-11e8-970b-29ddff41e341.png)
