### ISSUE TITLE
Extend vaadin-element-mixin

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-item#35]
Should be aligned with other vaadin core elements

**Comment by web-padawan** [comment]
Starting from v2.2.0-alpha1, there is a dependency and `Vaadin.DirMixin` is used.

From the Flow point of view, `vaadin-item` is an internal component, e.g. we don't have `vaadin-item-flow` repository. And we don't have to report usage for internal components.

Closing as won't fix.
